# Sudo required for doing docker build
sudo: required
services:
- docker

# Build the docker image
script:
- ./build/docker-build.sh

# If successful, see if we need to publish also
after_success:
- ./build/travis-publish.sh

# Environment variables needed when publishing
env:
  global:
  # DOCKER_USER
  # - secure: doqbzVBfhpEJVHmcqRqthf6Bj3E04rrNARheFcEsdavnuspcep760A7bxxaS39gvSm105QnT6QAqj2924L0SfWUF8cqlrnWmEkjCq+z0MkmRFcX6JqqFn9ltEPTGInKQuIsWYEIvmnDE6oMl9ShKa2o0jeEVdKBQfvYyUdxjgxy8wuVZSWR9iv+ymTfgfBBQ3+D4cn+srU6OVXP+MjlQLeGKLwJvjJhNZRSVZ5pr0J3bFXlhweYZRfe4XpqtW/77wzXsxWpXGlUNzTJNQ9Poi2c93nh8EM5UVKTqfts/VjQh9V1qVAdZcmCLSx+7+tdRqPGDe2O/ku0ZV4XvCsuWpuu6kWHjMrb9iueJSHQWE/SFAvmxky+pZk9kfaFSIyoBp9PQwpC925r9ajJ5CV2+SFjoJ5/CgGGNRxWunEzDavS+PItp4DbVTioa1etqYmI0m9doBbbWMybQoQUqY63QXsDMAoGJwA3X6TKkcIWrDKwzSYcRv3ef26lsRV36bQ0KVYpi5VKNWxIE+j6tjFYzoq12erUzpL12/MYbG63Vkpy36fWmMrOAkQMPBc2JN3oN6DbczROaTU+nYvwHlLwlZLAuadN7ogHYuuh2Q3BDZvzCVlQ93se8KXoCEyjeGC47kn/Mp1SOArvyAY20Uwr2gkEnixog341vf+Nq/Dq8CIc=
  # DOCKER_EMAIL
  # - secure: FwJO9prCbPl3GTyUVXNx8pxvcg9NxlleXmoSxBhIdhUFXmBe3qwY5i17iqSri0cP6HBtjvMVOC4warg8PqNA9I2hx8shO7J1h19+CsVm3VbjdWeo7dN1bJ+4oGxM9UadprE8u9hq/CCAVG1wVTDC7rV0uXIkW4DSr/XojEuZ6MQjDydp4pUeHu3eai3xpWPzkbMJxo+h3hVR7OBgHGb45zFHEfPFLlbKYXbt3bGjWmPas4Ez5/ho1nJbyjciXZMh2TzqyWsjUpsrMr/jZ+L/9LtKgjG/pg2P+qQOVWrkibftkAi8lJbXkHzYsyGytzp9pWBh5t+j7o6LCPhvwvkaH7U2IsOt/HuSmxES/0wUG+QtVgSU7xm0FEunZvM6EKKp4OZj1Z3DjTlHxp5kS18t4sxd+bX3t1PBFfSMHBFX3K6rSzmbxr9KGSPag3XatH035sxgfJa9otCBBpE3FF+h9t+AkFUg/JUW6hJ5eguxbRAXE0Jt5DNABUlgZZDdEBHVZA/hcTI8A5lCW015dY4OBYRMwiZj75IHwwNtU1LEPy7EvmB2eUYWsiSbX4pOE7LYeVEob4lN/a+kkDVFGWHmLi/jasFbCxTPpy7M85p3UtM/qiOWMslMB36VRjYft3W3GOmUuOG6OnyEqDlCz55yibwIHHMoiuaxJt5rpEzs4qE=
  # DOCKER_PASS
  # - secure: FIey0mnd5E/db4Z8RBmLuLXZM61DZ7LNyB/H7RU+IlqqUeeGMBhGSDJuditsl4R3xQuYsWZuVCJi+8YIS8M7QlpQ3oSyEWb9xVG0uFG/wC6+RiTG6qdyXJSIv3EUzXdBRaOi5Qnsq/XN/LFJOh/X4cX9nOJVQZsXluqdaf5ef4zcLDqOBhyFL7KqXGIhyD6Gv6NtADTCppYIomDabypYOsV1GC1BgptVJM12ogIa8lB7iVuAqgGXvqgnzLnyzMzTk6dhpiiAg8Ci5Tb6cTwmdl1Ot7J4Xtc11KdyDJYXNNR22Vb3/maX/wmEvETRE+8jp0tOS1hIKSIlooAw1vTgVQ8194hB9LAjFSxt5m7dyKg06SpdVBVwvfPkpEyT+SQgJpp+xpKvUplbNOPjcRwPzVKeWS6PpimovbywZyTshF6dr3p1ZwRfVSMZBZOn96Ay02zVUWEgSyAyjQOoVkPYqBDYBPFZyRpHSVWGFs/0pZWAMAv9Au7VCoEhlk7OB7cPi0OG5FbP2S/+alrDcjSRlX5zlv+Eqc1m2XMTxgP9zl3lGI0+PxqYXhvl+mYlMb1IGSICJH11XAGow5bhT8oE6K2ZGtT78R1SDIsjv8fpJyFfMyZPfJG+bJM70Le8l2vtPAKPWQ/KWrmzxrGPJx9KXw6LAeswdFIdTvP9KqOuz2E=
