# Sudo required for doing docker build
sudo: required
services:
- docker

# Build the docker image
script:
- ./build/docker-build.sh

# If successful, see if we need to publish also
after_success:
- ./build/travis-publish.sh

# Environment variables needed when publishing
env:
  global:
  # DOCKER_USER
  - secure: "k9p4M90vOofJkRaGAhp9o/l6yoPcmN1VanAsBz7mBTLx+WAn3NH55SG5ED0dt040fBvMOlk3b7qIOrh1loEQOIfKiRmq60CIvczV4f84E7oMGNpuUcJMMgDbbn72J9t/e48+8wADTKMhas3fSB/Dv2mitYMfZ6KY9oC+eSKCw/tPJnAw0OPqnKCqRbBmCqugdA5QLQ8pSokPV2XbbOJH72puOQzTywFXbaw12ZDB61LK7MKoJw36p+/9V05QhWUCUQAx20w8tznZ0eMkhLVcz+lCwKCfGMKEcw6dgiKEII9lrBvAqrELMWJ3l/YkVKMJ9C2OUSriaSHEMFUaGoArSSkI2GNaRlz+tSCFE8g/G/L6TUPZBQtzh4jXylOrqWxDYk0tJ3dCO4SRK0/L5zOoRuQtc3OWTlK6De51ek+rSK1cr7sBXRfJx+zf9b4OL7/jZDzbcPTLhZOxQWyipNnfeB7IB41rsRFKcn+BbF3ru/KL2AulEBPo/MmYvuf8oap9vFhYKKOE0w1lnKk6K/8L20LvvWWUEC6xY/ywngm2nrZZZN5/yTcTIe6HqEk8r+IgefZAGeTcoauTp9sAUsuwZoFjz7Mr81HJUiIBwe/enXB0LXyS4CE8WmSHhfrVaJksq1pOhZ2Lx/qHyGyjflrdRrun9FtHuVfvZ6dpWcs2xYg="
  # DOCKER_EMAIL
  - secure: "dA9VgYpjp91iIoXYnCoG2QLe6A56tc8czkTE6c9YCAFhxCp/BWgukzRhXRIIs9P2+TN6A09E/Udyyt6FGG4mHbOkfZyfE6CMRb+boyfFw0rFTdsAFjoPwSirKp4sd5PSFkjOzPTvxo5Qa7jUI12LFEwXffgsE24hvJ0s/cD7Co1uFaWycwc7fx9s2qPZi1xZpP84R7lIIK6IsWoUylzJy9Qoe53lE74m6p2donsXeAak49gR/86HKTxQ//gEX4ctPFxsMurqTTXifCREhutokNysI+FdcU18LEN4pZUzB+bl7p50l4rz+2D4sJY1tQTJ5Gds9oYXHe/ZJNg9V5A5JlaeY00giu4+1bNKoH9Lj488kjWyB7HucqwFNBkMdgnN6gshdlc0D2xEbXm/4/3UWzxEy7fDRBlGkDiofCHKOh2mpg4S5nsQ9OAFbnTdnQho8V2johLBRpHB8TL62sAG2GFHqP4om+LRRNAeexK8Vn2o291XtuogJ94vAxUwdfOx4ixmSJasMwaMrMySybycmqx/WTXO32PM4R5n2dw1VsZKVGzXkpkmHTP2w9Kt+/uJ6ZseV3ZXZvh0+53T5IFugj/CzAYo0BwTkaIfboFpRg3Go1lwxIKKg7RE8DRvU0N8JZyJhIcEzOKrvLkQL5tKDUCFCHRZRgaulM+GqEjpP8o="
  # DOCKER_PASS
  - secure: "Ug9Fcp3hROVxxVqFNbP/snuFsRTAKkZcZnQ7LrMJmbcImfifNf43Ytsd84SrSQdcjtEyFQLsjirX8Pot7pQuIQPHvQKLXjfhdh3XRFZzjc3NSHJjZ0JmRyxYIhFsoiDn3kUifip82Ptd7ReMjSVEHAbIt2rOtAZHqCgejX8s02bPYWRZTMkxGFqQ9cM/JRT406i8ue9RRtbBO0XyJdms0DLb8nJ6T7tOOycz6lOj9wacFyjcik/GHhJcBdJ6GvVWSzsOstQrkV//DyHb+AaFpxjYpj1LMMmQHqySBM20QIuKrcUMxrOZS37wbaUXilArmsNYh4QzQA/OvOj/lm1UxYyCe+luwjcdnpZtJWXPOLQfCRDxuExcfIEDBWLfYkg2giZGdnF9Tu8A4CEzOuTPk4c4TFle2x20x1lzm57FXawyv0Vq9C031oEvNR7BKLg0XhiJWi5hHjvP8ukish+yodUCU4T5pNldjV67LCKSI7kzZOBXz+wfnvGpABYsOu7suuQeIztx9VQkatZEEILPK2b4RLerPXwlA5BrzZOaSVUk+KX4wQhvJLQsgk+/lhdKJq9fj7M8twl3/6SoyMoKOGbMJ+HCuUhQt8BHHOElXaCktzJ8h1dRT18b+iPRcbFo2WZOzFqn+JS/cU0q3vpdG3fzXY7/pzd8cMJ5nCP7kY8="
  